server:
  port: 9209
spring:
  application:
    name: user-auth
  redis:
    host: 192.168.200.128
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.200.128:3306/kaola_user?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
    username: root
    password: root
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    cache: false
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka
auth:
  ttl: 3600  #token存储到redis的过期时间
  clientId: jd
  clientSecret: jd1234
  cookieDomain: .kaolayigou.com
  cookieMaxAge: -1
encrypt:
  key-store:
    location: classpath:/kaola.jks
    secret: kaolayigou
    alias: kaola
    password: kaolayigou